var lang_selected = config.data.language;
lang_selected = lang_selected == "english" || lang_selected == "russian" ? lang_selected : "english";
var lang = {
	"english": {
		"loading": "Loading...",
		"author": "Created by InfiniteC0re",
		"panel_library": "Library",
		"panel_script_editor": "Script Editor",
		"panel_config_builder": "Config Builder",
		"panel_customization": "Customization",
		"panel_settings": "Settings",
		"panel_chat": "Chat",
		"panel_website": "Website",
		"library_play": "Play",
		"library_desc": "You can play any of these games only if you have licenced Half-Life in Steam.",
		"save": "Save",
		"back": "Back",
		"saved": "Saved!",
		"editor_new_file": "New File",
		"editor_new": "New",
		"editor_open": "Open",
		"install": "Install",
		"preview": "Preview",
		"build_to_file": "Build to File",
		"binds": "Binds",
		"customization_backgrounds": "Menu Backgrounds",
		"customization_sprites": "Item Sprites",
		"customization_hud": "HUD Color",
		"customization_skyboxes": "Skyboxes",
		"customization_crosshairs": "Crosshairs",
		"sprites_standard": "Standard Sprites",
		"sprites_q3": "Q3 Styled Sprites",
		"start_settings": " - start settings",
		"build_desc": "Build your own config from ready presets.",
		"customization_desc": "You can change some elements of the games.",
		"backgrounds_desc": "Background you install will appear in all games.",
		"sprites_desc": "Sprites of dropped weapons and other items.",
		"hud_desc": "Bunnymod XT UI color changer.",
		"skyboxes_desc": "Skyboxes can be better.",
		"select_color": "SELECT COLOR",
		"skyboxes_better": "Better Quality Pack",
		"skyboxes_standard": "Standard Skyboxes Pack",
		"crosshairs_desc": "Crosshairs for every taste.",
		"misc": "Misc",
		"rpc": "Discord Rich Presence (Restart Required)",
		"light": "Switch To Light Theme",
		"dark": "Switch To Dark Theme",
		"chat_nickname": "Send '/name nickname' to change your nickname in chat.",
		"starting_game": "Starting Game...",
		"interface": "Interface",
		"lang": "Switch to Russian Language"
	},
	"russian": {
		"loading": "Загрузка...",
		"author": "Создано InfiniteC0re",
		"panel_library": "Библиотека",
		"panel_script_editor": "Редактор",
		"panel_config_builder": "Сборка конфига",
		"panel_customization": "Кастомизация",
		"panel_settings": "Настройки",
		"panel_chat": "Чат",
		"panel_website": "Вебсайт",
		"library_play": "Играть",
		"library_desc": "Вы можете играть только если имеете лицензию Half-Life в Steam.",
		"save": "Сохранить",
		"back": "Назад",
		"saved": "Сохранено!",
		"editor_new_file": "Несохранённый файл",
		"editor_new": "Новый",
		"editor_open": "Открыть",
		"install": "Установить",
		"preview": "Просмотр",
		"build_to_file": "Собрать в файл",
		"binds": "Бинды",
		"customization_backgrounds": "Фоны для меню",
		"customization_sprites": "Спрайты предметов",
		"customization_hud": "Цвет HUD'а",
		"customization_skyboxes": "Скайбоксы",
		"customization_crosshairs": "Прицелы",
		"sprites_standard": "Стандартные спрайты",
		"sprites_q3": "Q3 спрайты",
		"start_settings": " - параметры запуска",
		"build_desc": "Создайте свой собственный конфиг из предложенных заготовок.",
		"customization_desc": "Вы можете изменить некоторые элементы игр.",
		"backgrounds_desc": "Установленный фон появится во всех играх.",
		"sprites_desc": "Спрайты лежащих оружий или предметов.",
		"hud_desc": "Инструмент изменения цвета интерфейса Bunnymod XT.",
		"skyboxes_desc": "Скайбоксы могут быть лучше.",
		"select_color": "ВЫБРАТЬ ЦВЕТ",
		"skyboxes_better": "Набор улучшенного качества",
		"skyboxes_standard": "Стандартный набор скайбоксов",
		"crosshairs_desc": "Прицелы на любой вкус.",
		"misc": "Разное",
		"rpc": "Discord Rich Presence (Требуется перезапуск)",
		"light": "Переключиться на светлую тему",
		"dark": "Переключиться на тёмную тему",
		"chat_nickname": "Отправьте '/name никнейм', чтобы изменить свою имя в чате.",
		"starting_game": "Игра запускается...",
		"interface": "Интерфейс",
		"lang": "Switch to English Language"
	}
};